<?php require_once 'header.phtml'?>

<ul class="list-group">
    <li class="list-group-item">
        <nav class="navbar navbar-light btn">
        <a class="navbar-brand" href="discos">Ver y modificar discos</a>
        </nav>
    </li>
    <li class="list-group-item">
        <nav class="navbar navbar-light btn">
        <a class="navbar-brand" href="agregar">Agregar nuevo disco</a>
        </nav>
    </li>
</ul>
<?php require_once 'footer.phtml'?>