<?php 
require_once './templates/header.phtml';
// require_once './templates/form_alta.php';

?>

<h2>Discos</h2>
<ul class="list-group">
<?php foreach($discos as $disco): ?>
    <li class="list-group-item disco">
        <div>
            <b><?= $disco->title ?> (<?=$disco->dyear?>)</b> - <?=$disco->artist?>
        </div>
        <a href="detalleDisco/<?php echo $disco->album_id?>"><button class="btn btn-primary mt-2">Ver detalle</button></a>
        <a class='btn btn-danger btn-sm' href='eliminar/<?=$disco->album_id?>'>ELIMINAR</a>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> discos</small></p>